companieshouse/ch.gov.uk

templates/includes/transactions.tx
Removal reference to user ID from the 'Your Filings' page so this internal property is not exposed in the javascript.
Resolves [FAPI-2078](https://companieshouse.atlassian.net/browse/FAPI-2078)
=> Remove Reference to User ID from 'Your Filings' Page

cpanfile
`MojoX::Plugin::AnyCache` depends on an unversioned `Mojo::Redis` dependency, meaning the latest version available will be used. Recent version of `Mojo::Redis` have introduced an explicit dependecy on a version of `Mojolicious` greater than or equal to `7.30` (see https://github.com/jhthorsen/mojo-redis/blob/master/cpanfile#L2). During dependency resolution, this will cause a version of Mojolicious that satisfies this dependency to be installed (currently `7.85`) which does not match the declared version in the cpanfile for this project, hence causing runtime failures due to the removal of expected subroutines.
By adding an explicit versioned dependency of `Mojo::Redis` we ensure that the declared version of `Mojolicious` in the `cpanfile` is correctly resolved (version `5.47`).
=> Fix cpanfile comment with correct dependency name

appconfig.yml, lib/ChGovUk/Controllers/Company/FilingHistory.pm
flag is not used for any functional purpose so removing to avoid confusion going forwards
=> remove references to unused config item disable_download_xhtml_link

cpanfile, lib/ChGovUk/Controllers/Admin/Transaction.pm, lib/ChGovUk/Plugins/Admin/Routes.pm, templates/admin/transaction/transaction_reprocess.html.tx, templates/includes/transactions.tx
ℹ️ The changes here are part of a larger effort to introduce transaction reprocessing to the admin site.
A 'Reprocess transaction' button has been added to closed transactions on the admin site to permit users with the correct role to initiate transaction reprocessing.
**Related pull-requests:**
* https://github.com/companieshouse/account.ch.gov.uk/pull/300
* https://github.com/companieshouse/transactions.api.ch.gov.uk/pull/87
* https://github.com/companieshouse/Net-CompaniesHouse-Admin/pull/8
* https://github.com/companieshouse/cdn.ch.gov.uk/pull/274
=> Add transaction reprocessing functionality to admin site

templates/includes/transaction.tx
This changes introduces the 'Reprocess transaction' button to the individual transaction page for use by support staff.
=> Add transaction reprocessing support to individual transaction page

appconfig.yml, cpanfile, lib/ChGovUk/Controllers/Admin/User/Filings.pm, lib/ChGovUk/Controllers/User/Transactions/Resume.pm, templates/includes/transactions.tx
These changes remove the coupling between the 'save and resume' functionality and abridged accounts and replaces this with a generic mechanism for retrieving the resume link from the transaction resource.
**Related pull-requests:**
* https://github.com/companieshouse/abridged.accounts.web.ch.gov.uk/pull/554
* https://github.com/companieshouse/company-accounts.web.ch.gov.uk/pull/119
* https://github.com/companieshouse/transactions.api.ch.gov.uk/pull/89
These changes also include a fix for failing builds due to dependency resolution issues—the `Test::Exception` module has been added as an explicit test dependency.
Resolves: SFA-42
=> Refactor save and resume support

Makefile
This change adds support for pulling dependency packages from an S3 bucket rather than relying on our existing `getpan`-`gopan`-`smartpan` toolchain.
The existing `build` and `getpan` targets remain unchanged, so this will will have zero impact on the existing build job in Jenkins.
=> Add basic support for dependency packages

Makefile
This changes brings the dependency package version in line with the first artefact built from the pipeline deployed to Concourse CI: https://ci.platform.aws.chdev.org/teams/development/pipelines/ch.gov.uk-deps/jobs/release/builds/1.
=> Bump dependency package version

templates/search/banner.tx
The search bar which appears at the top of "company" pages contains duplicate form labels. A form control should have at most one associated label element. If more than one label element is associated to the control, assistive technology may not read the appropriate label.
**Resolves**: PCI-158
=> Accessibility fix: Remove duplicate form labels on CHS

templates/company/company_name_availability/form.html.tx, templates/company/follow/list.html.tx, templates/includes/company/page_header.tx, templates/includes/transactions.tx, templates/personal_appointments/get.html.tx, templates/search/form.tx, templates/static_pages/help/contact-us.html.tx, templates/static_pages/help/cookies.html.tx, templates/static_pages/help/guidance.html.tx, templates/static_pages/help/other-filings.html.tx
Content id required for skip link to work - however the id contains styling which throws off the pages style. An override class has been added to prevent this.
**Resolves**:  PCI-186
=> Update content ids so that the skip link works while not affecting page style

lib/ChGovUk/Controllers/Company/Document.pm, templates/company/document/scud.html.ep
* Changes made to SCUD API result in it returning 200 OK rather than 201 Created.
* Distinction not seen as being important and hence this client side validation has been loosened.
=> PCI-198: Loosen up condition for success to cover all 2xx responses

templates/company/company_name_availability/form.html.tx, templates/search/banner.tx, templates/search/form.tx
Automatically focusing a form control can confuse visually-impaired people using screen-reading technology. Therefore it should be removed from the search forms present in CHS.
**Resolves**: PCI-183
=> Accessibility - Remove autofocus from CHS form controls

templates/includes/piwik.tx
changes piwik.tx to behave same as account and monitor-gui
Resolves: piwik GET failing for STAGING (the http resource was wrongly converted to https)
(No issue for LIVE though, as both urls are https)
=> changes piwik.tx to behave same as account and monitor-gui

lib/ChGovUk/Controllers/Company/Transactions/ChangeRegisteredOfficeAddress.pm, lib/ChGovUk/Models/Address.pm, t/unit/ChGovUk/Models/Address.t, templates/company/transactions/change_registered_office_address.html.tx
Add a hidden field `reference_etag` to be sent when changing a registered office address. This is populated with the `etag` value returned by the ROA API
Resolves FA-271
=> Post etag when submitting a change of ROA

t/unit/CH/Util/DateHelper.t
The unit test for `is_current_date_greater` was using a future date that is now in the past. 
Fix it by calculating the future date based on today's date and prevent this from happening again.
=> Fix unit test using a future date now in the past

errors.yml, lib/ChGovUk/Models/Company/Transactions/ChangeRegisteredOfficeAddress.pm, templates/company/transactions/change_registered_office_address.html.tx, templates/company/transactions/current_address.html.tx
Display error when the address reference etag does not match the company profile etag
Move the hidden field next to the current address so that the error link takes you to the current address for review
Part of FA-396 and FA-397
Note this needs to be made a warning, not an error. Changes to handle warnings will be done later
=> Display etag mismatch error

lib/ChGovUk/Plugins/FormHelpers.pm, templates/company/transactions/change_registered_office_address.html.tx, templates/company/transactions/current_address.html.tx, templates/includes/forms/errors.html.tx
Create and display form warnings, currently the only warning being `etag-mismatch`
Move the hidden field back next to the other address fields since it is no longer linked from the error section
Part of FA-396 and FA-397
See #109
=> Display warnings

lib/ChGovUk/Models/Company/Transactions/ChangeRegisteredOfficeAddress.pm
Generate a POST request for change of ROA. Currently a PUT request.
* ROA API throwing an error: `error: ROA resource doesn't exist for PUT request`
* Found that an `update()` call being made on transaction instead of `create()`; resulting in a `PUT` request instead of the required `POST` request.
Resolves:
FA-605
=> FA-605 Generate POST request for ROA address change.

templates/company/view_all/view.html.tx, templates/includes/company/tab.tx, templates/includes/company/tabs.tx
The `aria-describedby` was causing accessibility failures therefore recommended to remove until further investigation.
Resolves: GCI-1038
=> Fix broken accessibility by removing aria-describedby

lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm, lib/ChGovUk/Controllers/Company/FilingHistory.pm, lib/ChGovUk/Plugins/Routes.pm, templates/base.tx, templates/company/filing_history/view_certified.html.tx, templates/company/filing_history/view_content_certified.html.tx, templates/includes/company/certified_page_header.tx
Reuse filing history code required to add new skeleton screen for certified documents which will provide a filing history of a company to the user to select which certified documents they wish to order.
CDN Changes: https://github.com/companieshouse/cdn.ch.gov.uk/pull/400
Resolves: GCI-1153
=> Certified documents alternate filing history screen

templates/company/transactions/transaction.tx, templates/includes/forms/select_field.html.tx, templates/register_of_disqualifications/list.html.tx
To make sure the accessibility statement is applicable for the change of roa and register of disqualifications page, some fixes where required. This includes fixing broken skiplinks and adding a missing label to a form action
Resolves: CB-1108
=> Accessibility Audit - Change ROA and Register of Disqualifications

templates/company/filing_history/view_content_certified.html.tx
- Enable the ability to order a document that is before the `unavailable_date` that has a associated image that has been scanned
- Remove cost for documents that are not available for order
Resolves: GCI-1354, GCI-1355
=> Ensure documents with associated images are orderable and remove cost for unorderable documents

appconfig.yml, templates/company/filing_history/view_content.html.tx
When a filing history document is not available to view/download due to it never being scanned an option is available to order a document.
Resolves: GCI-220
=> Add Request Document Button for SCUD Orders

lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
* Changes made to stop the `filing-history` and `certified-documents` pages sharing the same category selection filter key.
=> GCI-1244: Remove selected filters

templates/company/filing_history/view_certified.html.tx
With the previous checkbox solution the main content of the page was nested inside a `<form>` element, therefore the filters were changed to use a `<div>`. Since moving to a single order the page is no longer inside a form, the form element provides some level of styling. This revert fixes the mobile styling issue that regressed due to the content not being inside a form.
=> Fix filters mobile styling

appconfig.yml, templates/company/filing_history/view_content.html.tx
Replace references of scan upon demand to be missing image delivery
Resolves: GCI-1478
Dependent on PR: https://github.com/companieshouse/chs-configs/pull/1229
=> Update feature flag and url to be missing image delivery

lib/ChGovUk/Controllers/Company/ViewAll.pm, templates/company/view_all/view.html.tx
The order a certificate option on the more tab will now dynamically output the correct information within the what you'll need drop down when a company status is dissolved and has a company type which allows the ordering of a dissolved certificate.
Resolves: GCI-1204
=> Gci 1204 update more tab for dissolved certificates

lib/ChGovUk/Controllers/Company/FilingHistory.pm, templates/company/filing_history/view_content.html.tx, templates/company/transactions/document_download.html.tx
Add calls to Document API to check Content Type for filing history items which are of type application/zip
UK-144
As discussed, a future minor fix will also be carried out as part of https://companieshouse.atlassian.net/browse/UK-155. This work will involve changing the _get_content_type sub to correctly return an array and for the view_content.html.tx to correctly handle this new logic and display the correct links.
=> Filing History Content Type

lib/ChGovUk/Controllers/Company/FilingHistory.pm
Before this fix, the sub routine would only return the first
content_type that it found in the resrouces array. This was
only temporary to meet a strict deadline.
This change means that the sub routine will now loop through
the resources array that is returned from doc api
and attempt to find the content_type we want and set it
correctly.
=> Fix temporary implementation of get_content_tye sub

lib/ChGovUk/Transaction.pm, templates/error.html.tx
- Update title to use error description and add service name and govuk to the title.
- Add descriptions to errors where it was missing.
Resolves: CHS-2052
=> Update error page titles to provide detail for screen readers

templates/base.tx, templates/company/filing_history/view_certified.html.tx
Flag was only used on the certified documents filing history ordering screen. Therefore the flag can now be completely removed as it is now required in certified documents.
Resolves: BI-8844
=> Remove flag that prevents accessibility statement showing

errors.yml, lib/ChGovUk/Controllers/Company/Mortgages.pm, lib/ChGovUk/Controllers/Company/Pscs.pm, lib/ChGovUk/Controllers/Company/Registers/Pscs.pm, lib/ChGovUk/Controllers/RegisterOfDisqualifications.pm, lib/ChGovUk/Controllers/Search.pm, lib/ChGovUk/Controllers/Search/CompanyNameAvailability.pm, lib/ChGovUk/Plugins/Bridges.pm, lib/ChGovUk/Transaction.pm, templates/error.html.tx
Description cannot be used in all error pages and many error types are not defined. This PR adds a error constant for all error types to enable use of the errors constants for page titles.
Resolves: CHS-2052
=> Update error page rendering to display correct titles for all error pages

templates/static_pages/help/accessibility-statement.html.tx
A bug was found in chrome for screen readers where
if a user has used a page before, the screen reader
will fail to read any labels above any text boxes
that have been previously used. This results in users
not being able correctly use the service.
**Resolves BI-9142**
=> Update statement to reflect new bug found in chrome

templates/includes/transaction.tx, templates/includes/transactions.tx
Do not display view link on admin screen for non account transactions
Filing types for account transactions taken from: https://github.com/companieshouse/chips-filing-consumer/blob/fe2fd358776d57159cc03a54bc40fe1e9a81b12b/src/main/java/uk/gov/ch/services/documentinput/FilingTypes.java
Resolves: https://companieshouse.atlassian.net/browse/NCS-667
=> Remove view link for non accounts transactions

templates/company/filing_history/view_content_certified.html.tx
update logic for initial check of pre95 and pre95m types 
add a td to complete the empty column styling
Resolves: BI-10160
=> Prevent pre95 cert docs to be orderable

templates/company/filing_history/view_content.html.tx
Add additional `govuk-link` class to the download ixbrl link so that all links present on the filing history have the correct link styling and behaviour.
Resolves: BI-10372
=> BI-10372 - Add govuk-link to download ixbrl link

templates/company/filing_history/view_content.html.tx
Currently there is a bug in live where ixbrl download link does not appear
for revised/amended accounts. Fix is to add `AAMD` in the check to make sure
revised accounts are also added to display the download link.
Resolves: BI-10339
=> Fix issue with Revised Accounts

templates/base.tx, templates/company/filing_history/view_content.html.tx
The `Download IXBRL` link does not trigger the visited attribute as it never leaves the page. A work around for this is to update the colour of the link to replicate the behaviour of govuk's visited styles.
Resolves: BI-10372
=> BI-10372 - Enable download ixbrl link to update colour when clicked

templates/base.tx, templates/company/filing_history/view_content.html.tx
A number of mobile browsers are not compatible with the visited styles provided by gov-uk. For consistency this enables the links to use the visited styles.
Resolves: BI-10372
=> BI-10372 - Enable link to use visited style on non compatible browsers

lib/ChGovUk/Plugins/AddressHelper.pm, t/unit/ChGovUk/Plugins/AddressHelper.t, templates/company/officers/list.html.tx
Ensure that names present in contact details for managing officers are displayed.
Resolves: ROE-177
=> ROE-177 - Include names in managing officer contact details

templates/personal_appointments/get.html.tx
Move logic from entire identification section to the `What's this` section as that is the only part not required for managing officers.
=> Fix logic placement to ensure not all identification sections are hidden for corporate ROA officers

templates/company/pscs/list.html.tx
allow roe companies to output bo data when name is missing
Resolves: ROE-632
=> allow roe companies to output bo data when name is missing

templates/company/pscs/list.html.tx
output secure psc or secure bo or bo if name is not available
Resolves: ROE-632
=> add output for a super secure bo when name is not available

templates/company/view.html.tx
Update annual update section to use _statement_ instead of _update_.
Resolves: ROE-836
=> ROE-836 - Amend annual update section to use statement wording

appconfig.yml, lib/ChGovUk/Controllers/Company/BasketClient.pm, lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm, t/unit/ChGovUk/Controllers/Company/BasketClient.t, templates/company/filing_history/view_content_certified.html.tx
* Link text on certified document selection page changed to "Add to basket" if user enrolled.
* POST new item to appendItemToBasket endpoint.
* Enrolled user redirected to /basket if deliverable items already in basket.
* Enrolled user redirected to /delivery-details if no deliverable items already in basket.
Resolves:
[GCI-2156](https://companieshouse.atlassian.net/browse/GCI-2156)
=> GCI-2156 Append certified documents to basket if user enrolled

lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
* ChGovUk::Controllers::Company::CertifiedDocuments should redirect user
agent to /orderable/certified-copies/{id}/delivery-options if user is
enrolled or not.
=> Fix incorrect redirect URL in cert doc handler

templates/includes/transactions.tx
add govuk hidden css class to empty table header
Resolves: GCI-2231
=> add govuk hidden css class to empty table header

templates/company/view.html.tx
- Fix company type overviews that did not work with the new tab panel upgrade due to bad html
- Fix field showing which likely should not be shown (Waiting on analyst confirmation)
=> Fix broken overview company types from tab panel upgrade

lib/ChGovUk/Controllers/Search/CompanyNameAvailability.pm, templates/base.tx, templates/exception.production.html.tx
* Duplicate implementation from the home page to this page.
* Change implementation to chain fetching of search results after successful fetching of basket link info.
* Use built-in error page in case of issue accessing basket info.
* Tweak error page to include contact us link rather than request to email us. 
* Confirm no automated tests broken by changes.
=> BI-11898: Company name availability basket link

lib/ChGovUk/Controllers/StaticPages.pm
* This should render the basket link when appropriate on static pages such as the `Is there anything wrong with this page?` page and the `Other document filings` page.
* Refactored home page basket link code in same controller to reduce code duplication.
=> BI-11899: Add basket link to static pages

lib/ChGovUk/Controllers/Search/CompanyNameAvailability.pm
- Correct log type from `HOMEPAGE` to `COMPANY_NAME_AVAILABILITY` to detail where logs are spawned
- Ensure rendering of page on errors and failures from the call to getBasket
- Reduce code duplication
Resolves: GCI-2385
=> Fix issue where page not rendering on failure and error of get basket

lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
- Redirect back to the certified documents start page rather then the filing history page following log in.
=> BI-12132: Redirect back to same start page following log in

README.md, templates/includes/transactions.tx
https://companieshouse.atlassian.net/browse/ROE-1694
* Hyperlink of company name on Your filings screen does not
work if company number is not present in the transaction.
* This is the case for OE registrations, new incs etc.
* Company name now no longer displays with a hyperlink if
company number is not present
* README file updated with help suggestion if 'make' fails
=> ROE-1694 - TL - Suppress display of hyperlink if no company number

templates/includes/company/page_header.tx
[ROE-2191](https://companieshouse.atlassian.net/browse/ROE-2191)
trackEvent requires two arguments: category and action 
Without them it fails validation and gives an error in the 
javascript console and no event is sent to Matomo.  
It probably used to work before Matomo fixed the validation in 2018.
https://github.com/matomo-org/matomo/pull/15980/files
[ROE-2191]: https://companieshouse.atlassian.net/browse/ROE-2191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ROE-2191 Add required second argument to trackEvent

templates/company/filing_history/view_content_certified.html.tx, templates/company/follow/list.html.tx
[DB-1952](https://companieshouse.atlassian.net/browse/DB-1952)
trackEvent requires two arguments: category and action Without them it fails validation and gives an error in the javascript console and no event is sent to Matomo. It probably used to work before Matomo fixed the validation in 2018. https://github.com/matomo-org/matomo/pull/15980/files
[DB-1952]: https://companieshouse.atlassian.net/browse/DB-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DB-1952 Add required second argument to trackEvent

templates/includes/company/page_header.tx
Fix for defect: https://companieshouse.atlassian.net/browse/ROE-2265
* Template changed to ensure that the link no longer appears for OE companies
=> ROE-2265 Suppress the 'Manage Company Authentication' link

templates/company/view.html.tx
Add annual statement overdue indicators for ROE companies and clean up formatting for annual/confirmation statement section of template.
**Note**: The code change is present in the second commit. The first commit relates to formatting.
**Resolves**: BI-13246
=> BI-13246 - Add annual statement overdue indicators for ROE companies

lib/ChGovUk/Controllers/Company/Transactions/ChangeRegisteredOfficeAddress.pm, templates/company/transactions/appropriate_address_statement.html.tx, templates/company/transactions/change_registered_office_address.html.tx, templates/includes/forms/checkbox.html.tx
Added checkbox & summary text for appropriate address statement to registered office address change, to be shown only when property ecct (FEATURE_FLAG_ENABLE_ECCT_01092023) is set.  (Data not yet used in onward code, to be addressed in separate ticket).
Modified existing checkbox.html.tx to support this - so far this appears
only to be used by secure_address.tx, which does not itself appear to be
used.
=> Add appropriate address statement [ECCT-516]

templates/company/transactions/change_registered_office_address.html.tx, templates/company/transactions/transaction.tx, templates/includes/forms/errors.html.tx
Updated error message handling:
- error box is placed above page heading
- error box title corrected & additional text removed
- page title updated with 'Error: ' prefix - note that this was done as script since title is not currently re-rendered when errors are returned
=> Update error message display [ECCT-547]

lib/ChGovUk/Controllers/Company/Pscs.pm, t/unit/ChGovUk/Controllers/Pscs.t
Previously only the first active statement would be present at the top of ROE companies beneficial owners. This change allows all active statements to be placed at the top.
The order will now be as follows if present:
1) Active statements
2) PSC's/Beneficial Owners
3) Withdrawn statements
Resolves: BI-13504
=> Update ordering of active statements for ROE companies

lib/ChGovUk/Controllers/Company/Officers.pm
* This code will not be hit regularly once [DSND-2549](https://companieshouse.atlassian.net/browse/DSND-2549) has been implemented, although it is still makes sense to render the message.
* Fixes: [DSND-2588](https://companieshouse.atlassian.net/browse/DSND-2588)
[DSND-2549]: https://companieshouse.atlassian.net/browse/DSND-2549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSND-2588]: https://companieshouse.atlassian.net/browse/DSND-2588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2588: Display no officers messages on officers tab when officers list returns 404

templates/company/filing_history/view_content_certified.html.tx
Fulfils [BI-13513](https://companieshouse.atlassian.net/browse/BI-13513)
Prevent PRE-87 packages being ordered via certified copies ordering service
[BI-13513]: https://companieshouse.atlassian.net/browse/BI-13513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-13513 - Extend previous pre-95 logic to include PRE87, PRE87A and PRE87M type documents

templates/company/filing_history/view_content_certified.html.tx
Fulfils [BI-13650](https://companieshouse.atlassian.net/browse/BI-13650)
Prevents 'Select Document' link from being displayed if document does not have metadata
[BI-13650]: https://companieshouse.atlassian.net/browse/BI-13650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-13650 - Update OR to AND logic in certified document ordering

templates/base.tx, templates/register_of_disqualifications/list.html.tx, templates/search/results.html.tx
Reverting accessibility changes made for:
- BI-13628
- BI-13629 
This has been done as more considerations need to be made before this can progressed and to unblock BI-13686 and ECS routing changes from progressing to Staging/Live.
**Note for re-implementatoin**
The styles that were added for these stories should be moved the `cdn.ch.gov.uk` instead of being inline within the `base.tx` template.
PR's that were reverted:
https://github.com/companieshouse/ch.gov.uk/pull/463
https://github.com/companieshouse/ch.gov.uk/pull/468
https://github.com/companieshouse/ch.gov.uk/pull/469
=> BI-13628, BI-13629 - Revert accessibility changes 

templates/company/filing_history/view_content_certified.html.tx
Resolves [GCI-2576](https://companieshouse.atlassian.net/browse/GCI-2576) 
Remove check for unavailable date message and display docs if there is metadata available to resolve issue where links are not appearing 
[GCI-2576]: https://companieshouse.atlassian.net/browse/GCI-2576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove check for unavailable date message on certified-docs

templates/company/filing_history/view_content_certified.html.tx
Resolves [GCI-2576](https://companieshouse.atlassian.net/browse/GCI-2576)
Exclude PRE14s from being included in logic allowing for users to order images if metadata link/ image is available
[GCI-2576]: https://companieshouse.atlassian.net/browse/GCI-2576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> exclude pre14s from order if metadata link exists

lib/ChGovUk/Controllers/Company/Document.pm, lib/ChGovUk/Controllers/Company/Insolvency.pm, lib/ChGovUk/Controllers/Company/Mortgages.pm
Examples atm:
Failure fetching filing history item for company_number [<num>] filing_history_id [<id>] 
Error retrieving company insolvency for SC555768: Mojo::Transaction::HTTP=HASH(0x9883338) 
Error retrieving company filing for 02464002: Mojo::Transaction::HTTP=HASH(0xa2ee118)
=> Include error message in logs for a few regularly failing endpoints

lib/ChGovUk/Controllers/Company/Document.pm
When an image is not present it is returning a 500 error in the logs. This has happened around 2 million times in the last 7 days. This PR is an attempt to address the issue that is filling the logs in live.
=> ASM-434 - Add checks for 404's to document controller and change error to 404

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
Prevents an apply-time error when creating an ECS service with no listener rule but an active target group is specified.
This workaround instead always creates the listener rules but populates it the a placeholder value prefixed with `DISABLED`
=> Updated listener enablement logic

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/variables.tf
Bumped `ecs-service` module verisons to enable creation of CloudWatch service dashboards
Add supporting per-service vars and added required module argument.
=> Create ECS Service Dashboards

terraform/groups/ecs-service/main.tf
Adds missing args to `officers` and `default` services:
- `service_autoscale_scale_in_cooldown`
- `service_autoscale_scale_out_cooldown`
=> Ensure scaling cooldowns are correctly specified

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
As it is now expected that the next live release of ch.gov.uk will be to Mesos rather than ECS, revert the cidev and staging environments to Mesos for testing
=> Switch back to Mesos

terraform/groups/ecs-service/data.tf, terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/variables.tf
Adds modules to independently define ECS clusters for each service
Added data resources to lookup / retrieve data
Added supporting vars and locals
Added additional `use_fargate` vars so each service can be reconfigured independently
=> Service-specific ECS Cluster & Capacity

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/variables.tf
Add new vars and locals to allow per-profile use of dedicated ECS clusters
Update all ECS service modules to use new locals
Updated profile vars to set CPU and Mem and enable use of dedicated cluster for Officers service
Bump module versions
=> Cidev officers use cluster

terraform/groups/ecs-service/locals.tf
Ensure the correct service names are passed to the appropriate `trimprefix` and `replace` function calls.
=> Correct Function Service Names

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
Updates Search and the default service to use the dedicated clusters
Switch from Fargate to EC2 capacity
=> Enable use of dedicated clusters for default and search services

terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
* Enable ECS listeners for ch.gov.uk in Staging so we can draw a comparison between performance test search results gathered on the 2nd June when they were on.
[BI-14495](https://companieshouse.atlassian.net/browse/BI-14495)
[BI-14495]: https://companieshouse.atlassian.net/browse/BI-14495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-14471: Switch Staging back to ECS for search performance testing
