companieshouse/ch.gov.uk

- templates/includes/feedback.tx
Add link to guidance on how to stop CH from publishing your address
Resolves DS-92
> Add link to guidance on how to stop CH from publishing your address

- appconfig.yml
- templates/includes/feedback.tx
Updates the chs feedback form to include an authentication field also includes the config for feature flag.
Configs: https://github.com/companieshouse/chs-configs/pull/385
Javascript: https://github.com/companieshouse/cdn.ch.gov.uk/pull/251
> text file and config flag for auth code feedback form

- cpanfile
- templates/includes/transaction.tx
- templates/includes/transactions.tx
update to alter the transaction and transactions.tx templates to supply the link resource as the resource_url and remove the resourceID
Linked to SFA - 911 and 782
> update transaction and transactions.tx templates

- templates/company/officers/list.html.tx
- templates/company/registers/directors/list.html.tx
- templates/company/registers/members/list.html.tx
- templates/company/registers/secretaries/list.html.tx
Changed the types to uk-limited-company and other-corporate-body-or-firm
EUX-1024
> changed identification type for uk and non-uk

- templates/company/officers/list.html.tx
- templates/company/registers/directors/list.html.tx
- templates/company/registers/members/list.html.tx
- templates/company/registers/secretaries/list.html.tx
Changed the descriptions of the identification types so that they are now capitalised.
> changed the identification type on screen to be capitol

- templates/includes/feature_info.tx
- templates/static_pages/help/guidance.html.tx
> Update template wording to include full accounts

- templates/static_pages/help/corporate-officer-identification-type.html.tx
Update Text on 'Whats this screen'. This can be seen when a user click on 'Whats this' on the officer srceen.
Jira - 1033
> update this screen text

- appconfig.yml
> Change file accounts link to go to hmrc page

- appconfig.yml
Resolves: SFA-1277
Related PR: https://github.com/companieshouse/chs-configs/pull/497
> Update flag to use env variable

- templates/company/filing_history/view_content.html.tx
Updated the text if the image isnt available for a transaction within the filing history
Resolves : INC0223136
> update text for unavailablee image : INC0223136

- templates/base.tx
Add survey link to CHS footer
Resolves: PCI-87
> Add survey link to footer

- lib/ChGovUk/Controllers/Admin/User/Filings.pm
- templates/includes/transactions.tx
This change allows transactions with status "closed pending payment" to be resumed in the Your Filing section of ch.gov
[SFA-1739]
> fix for resume link on ch.gov my filing page

- templates/base.tx
reinstate disclaimer link after an update
> Added disclaimer link

- templates/base.tx
- templates/includes/feedback.tx
- templates/static_pages/help/feedback.html.tx
- templates/static_pages/help/other-filings.html.tx
- templates/static_pages/home.html.tx
Update landing page to use the new banner.
**Resolves**: PCI-84
> Add new banner and footer to CHS landing page

- templates/base.tx
- templates/company/company_name_availability/form.html.tx
- templates/company/follow/list.html.tx
- templates/includes/company/page_header.tx
- templates/includes/transactions.tx
- templates/personal_appointments/get.html.tx
- templates/search/form.tx
- templates/search/noresults.html.tx
- templates/search/results.html.tx
- templates/static_pages/help/contact-us.html.tx
- templates/static_pages/help/cookies.html.tx
- templates/static_pages/help/guidance.html.tx
- templates/static_pages/help/other-filings.html.tx
- templates/user/transactions/list.html.tx
Add skip links functionality to web pages
Resolves: PCI-159
> Add skip links functionality

- templates/base.tx
> Hotfix - Fix footer link

- appconfig.yml
- lib/ChGovUk/Controllers/Company/ViewAll.pm
- lib/ChGovUk/Plugins/Routes.pm
- templates/base.tx
- templates/company/view_all/view.html.tx
- templates/includes/company/tab.tx
- templates/includes/company/tabs.tx
- Add new tab to company profile screen
- Add view all tab screen
- Add generate company report button
Resolves: PCI-115, PCI-116
> Generate company report tab and button

- .gitignore
- .idea/runConfigurations/ch_gov_uk_on_chs_dev.xml
- appconfig.yml
- cpanfile
- lib/ChGovUk/Controllers/Company/Document.pm
- lib/ChGovUk/Plugins/Routes.pm
- start_debug.sh
- templates/company/document/scud.html.ep
- templates/company/filing_history/view_content.html.tx
* Changes made to `ch.gov.uk` to make it possible to submit a request to the new SCUD API POC (`scud.api.ch.gov.uk`) from the filing history page.
* Where the document is not available online, a green button is enabled that allows the user to request the document from the SCUD team.
* The rendering of the button and the order submitted/error reporting page is very basic and probably does not adhere to any relevant UI design guidelines.
> PCI-197 SCUD Web POC

- templates/base.tx
adds call to the Google Analytics js for gov.uk (GDS unique account)
> adds call to the Google Analytics js for gov.uk (GDS unique account)

- templates/company/view_all/view.html.tx
> Add piwik event for the generate company report button

- templates/includes/company/tab.tx
view all button was blue, should have been the same as other tabs
resolves PCI-240
> Correct view all button colour

- templates/includes/piwik.tx
Rebases for testing 
https://github.com/companieshouse/ch.gov.uk/pull/88
on 4.36.rc4
> changes piwik.tx to behave same as account and monitor-gui

- templates/company/view_all/view.html.tx
- templates/includes/piwik.tx
> Fix piwik heading and correct page title

- templates/company/partial_data_available/view.html.tx
Updates api-enumerations submodule for
SUP-272
https://github.com/companieshouse/chs-backend/pull/755 
https://github.com/companieshouse/api-enumerations/pull/136   
https://github.com/companieshouse/abridged.accounts.api.ch.gov.uk/pull/412
https://github.com/companieshouse/api.ch.gov.uk/pull/520
https://github.com/companieshouse/ch.gov.uk/pull/67
https://github.com/companieshouse/document-generator/pull/151
After SUP-248 was merged
https://github.com/companieshouse/ch.gov.uk/pull/96
https://github.com/companieshouse/api.ch.gov.uk/pull/523
https://github.com/companieshouse/abridged.accounts.api.ch.gov.uk/pull/415
https://github.com/companieshouse/extensions-web/pull/23
https://github.com/companieshouse/document-generator#199
replaced (after SUP-248 was merged) by …
> bumps submodule api-enumerations (SUP-272)

- appconfig.yml
- templates/includes/feature_info.tx
Add section to other useful tools which is feature flagged to provide users access to alphabetical search 
Resolves: PCI-227
> Add alphabetical search section to other useful tools

- templates/includes/feature_info.tx
> Update Piwik for Alphabetical company search link

- templates/includes/feature_info.tx
- templates/includes/piwik.tx
> Update piwik method to cater for piwik-events on root page

- lib/ChGovUk/Controllers/Company/ViewAll.pm
- templates/company/view_all/view.html.tx
Add order certificate to view all page
Update controller with logic to determine which items to display on the view all page
Resolves: PCI-554
> Pci 554 update view all tab

- lib/ChGovUk/Plugins/Routes.pm
- templates/company/view_all/view.html.tx
- templates/includes/company/tabs.tx
- templates/includes/piwik.tx
Change view all tab name
Update routes file
Resolves: PCI-554
> Pci 554 change view all tab name

- appconfig.yml
- templates/company/view_all/view.html.tx
> add order certificate feature flag

- templates/search/results.html.tx
Add guidance dropdown to officer search to make user aware of advanced search features
Note: Unable to test locally as search is not switched on in vagrant environments
Resolves: PCI-644
> Update Officer Search Guidance

- templates/search/results.html.tx
Ensure details element is closed when the page is loaded
Resolves: PCI-644
> Make details element closed by default

- templates/company/view_all/view.html.tx
update link to certificates orders web front end to pass company number
Resolves: PCI-792
> update link to certificates orders web front end

- templates/company/view_all/view.html.tx
- templates/includes/company/tab.tx
- templates/includes/company/tabs.tx
- Update Order a certificate section with latest text changes
- Add screen reader text to the more tab to increase accessibility 
Resolves: GCI-933
> Update order a certificate section and add screen reader text to more tab

- templates/company/view_all/view.html.tx
- templates/includes/company/tab.tx
- templates/includes/company/tabs.tx
> Add fix for aria-describedby not being linked to another element

- templates/static_pages/help/contact-us.html.tx
INC0266121 - update to the 'contact us' page : FESS
> INC0266121 - update to the contact us page : FESS

- appconfig.yml
- templates/company/mortgages/view_content.html.tx
Resolves: BI-3030 
Add a satisfy link to all outstanding charges that redirects to Webfiling login
> Add "Satisfy" link to all outstanding charges 

- templates/company/filing_history/view_content.html.tx
INC0266819 : 
update Filing History text is image unavailable : FESS
> INC0266819 : update Filing History text is image unavailable : FESS

- templates/company/view_all/view.html.tx
> Rename IDs to distinctive names

- appconfig.yml
- lib/ChGovUk/Controllers/Company/ViewAll.pm
- templates/company/view_all/view.html.tx
Add validation to check company type and filing history to display new section
Add feature flag for order a certified document section
Resolves: GCI-859
> Add order certified document section to more tab page

- templates/company/view_all/view.html.tx
> updated text to match prototype

- templates/base.tx
- templates/static_pages/help/accessibility-statement.html.tx
- Add new screen for the **Assessibility statement**
- Add alternative skiplink as `#content` id has styling that breaks page formatting
Resolves: CB-1108
> Add new accessibility statement screen to CHS

- templates/company/filing_history/view_content_certified.html.tx
- templates/includes/company/certified_page_header.tx
> Fix padding and change checkbox ids to be more predictable for automated tests

- templates/static_pages/help/accessibility-statement.html.tx
> Add missing 'e' to Statement in the page title

- templates/base.tx
- templates/company/filing_history/view_certified.html.tx
> Remove accessibility statement from certified docs filing history until audit

- lib/ChGovUk/Controllers/Company/ViewAll.pm
Removed scottish partnerships from certs orders list in controller
Resolves GCI-1275
> remove scottish partnerships from certs orders list

- lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
- templates/base.tx
- templates/company/filing_history/view_content_certified.html.tx
- Update checkboxes to use `transaction_id`
- Add link to `certified_documents_filing_history.js`
Resolves: GCI-862
> Update certified documents filing history for js add documents functionality

- templates/company/filing_history/view_content_certified.html.tx
Fix accessibility issue with labels missing which had regressed
> Regression - Add missing labels for checkboxes

- templates/base.tx
- templates/includes/company/certified_page_header.tx
Added links to go back to start now page
resolves: GCI-1221
> Added links to go back to start now page

- templates/static_pages/help/contact-us.html.tx
FESS - update the contact information.
> FESS : updating contact details for CHS

- templates/base.tx
* Replacing external js library with internal library
> BI-4548 replace external js lib

- lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
- lib/ChGovUk/Plugins/Routes.pm
- templates/company/filing_history/view_certified.html.tx
- templates/company/filing_history/view_content_certified.html.tx
- templates/includes/company/certified_page_header.tx
Post selected filing history to certified copy api
resolves: GCI-1056
> Gci 1056 post filing history

- lib/ChGovUk/Plugins/FilterHelper.pm
* Prevent sft cookie from being set multiple times in response headers.
> BI-4549 Set sft cookie on dispatch, not action

- lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
Fixed issue found in test, where if a single filing history was selected the application would crash.
resolves: GCI-1056
> Single filing history selection

- lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
- templates/company/filing_history/view_certified.html.tx
- templates/includes/company/certified_page_header.tx
- templates/includes/company/errors.tx
create new error template fragment
add show error reference in parent template
add check to certified doc POST controller to pass error variable to template
Resolves GCI-1220
> Displays error message when no documents are selected upon form submission on filing page

- appconfig.yml
- templates/company/filing_history/view_content_certified.html.tx
- templates/static_pages/help/accessibility-statement.html.tx
- Update contact details section to reflect re-opening of contact centre
- Feature flag the updated text and existing so that they can be switched in the event of another office closure due to COVID-19
Resolves: CB-1114
> Update contact details to reflect re-opening of CH Contact Centre - Accessibility page

- templates/static_pages/help/accessibility-statement.html.tx
Add missing `<ul>` closing tag flagged in lighthouse accessibility report
> Add missing closing tag to fix lighthouse accessibility report

- templates/company/company_name_availability/form.html.tx
> Fix empty header causing accessibility issues

- templates/company/view_all/view.html.tx
[GCI-1399](https://companieshouse.atlassian.net/browse/GCI-1399)  Update texts on order a certified document 
- from "to choose the documents you want to be certified" -> to "to choose the document you want to be certified"
- from "the address you want the documents to be delivered to (UK or international)" -> to "the address you want the document to be delivered to (UK or international)"
> Update texts on order a certified document

- templates/includes/feature_info.tx
- Add certificates and certified copies bullet point with `New` tag
- Remove `New` tag from Change a registered office address bullet point
Resolves: GCU-1513
> Update the CHS search screen for certificates/certified copies

- templates/company/filing_history/view_content.html.tx
> Update url to reflect web app url change

- appconfig.yml
- templates/company/view_all/view.html.tx
add feature flag to more tab for ordering dissolved cert
Resolves: GCI-1544
> add feature flag to more tab for ordering dissolved cert

- templates/company/view_all/view.html.tx
Change link within ch.gov for a dissolved certificate journey
> GCI-1579: Change link within ch.gov for a dissolved certificate journey

- lib/ChGovUk/Controllers/Search.pm
- templates/search/results.html.tx
* Remove highlighting from CHS company, officers, PSC searches.
> BI-5794 Remove highlighting

- templates/company/company_name_availability/form.html.tx
* Escape title, description and snippet fields.
> BI-5797 Escape fields in company name availability checker

- appconfig.yml
- templates/base.tx
- templates/static_pages/help/feedback.html.tx
> GCI-1646 - Add flag to enable/disable feedback form link and content

- templates/company/officers/list.html.tx
Updated officer's text from placed to place.
Resolved: BI-5996
> Update officer place registered

- templates/company/registers/members/list.html.tx
Updated member's text to place from placed.
Resolved: BI-5999
> Updated placed to place for members

- templates/company/registers/directors/list.html.tx
Updated placed to place on directors register.
Resolved: BI-5997
> Updated placed to place on directors register

- templates/company/registers/secretaries/list.html.tx
Changed placed to place for secretaries
Resolved: BI-5998
> Changed placed to place for secretaries

- templates/company/filing_history/view_content.html.tx
Added in logic to check the date and display a message depending on i…f it is pre or post 1/03/2003. Also if pre 2003 it will show the link to order, otherwise the link will be missing
> Added in logic to check the date 

- lib/ChGovUk/Controllers/Company/FilingHistory.pm
- templates/company/filing_history/view_content.html.tx
> Fixed so that it shows the correct message post 2003

- templates/company/filing_history/view_content.html.tx
Both messages won't display. The correct message should now be displayed. 
Resolves: GCI-1726
> Added in a check for double message error

- appconfig.yml
- templates/includes/feature_info.tx
Add dissolved search link to "Other useful tools" on chs homepage
Resolves: BI-66240
> add dissolved search link

- templates/includes/feature_info.tx
Added in Piwik event to company name availability
Resolves: GCI-1746
> GCI-1746- Added in Piwik event to company name availability

- templates/base.tx
Remove govuk ganalytics script tags
> Remove govuk ganalytics script tags

- templates/base.tx
- templates/includes/cookie-consent-banner.tx
- templates/includes/piwik.tx
- templates/static_pages/help/cookies.html.tx
Updates the cookie page to include accept and reject functionality
> Update cookie page with accept/reject functionality

- lib/ChGovUk/Controllers/Company/FilingHistory.pm
- templates/company/filing_history/view_content.html.tx
- templates/company/transactions/document_download.html.tx
Reverts companieshouse/ch.gov.uk#209
> Revert "Filing History Content Type"

- lib/ChGovUk/Controllers/Company/FilingHistory.pm
- templates/company/filing_history/view_content.html.tx
- templates/company/transactions/document_download.html.tx
Reverts companieshouse/ch.gov.uk#214
We had to temporarily remove our new UKSEF code for cookie consent work to be carried out safely in staging. This is completed now and we are confident that our code is safe to be re-enabled.
> Revert "Revert "Filing History Content Type""

- templates/company/view_all/view.html.tx
update text for certs and cert copies more tab
Resolves: BI-7071 & BI-7070
> update text for certs and cert copies more tab

- lib/ChGovUk/Controllers/Company/Pscs.pm
Amendments for PSC EU regulated market exemptions
Resolves
BI-8000
> Amendments for PSC EU regulated market exemptions

- lib/ChGovUk/Controllers/Company/Pscs.pm
Removed dtr5 statement from psc controller
Resolves BI-8003
> Removed dtr5 statement from psc controller

- templates/company/view_all/view.html.tx
Update more tab certificate title for both active and dissolved companies to 'Order a certified certificate'
Resolves: BI-8181
> BI-8181 - Update more tab certificate title 

- lib/ChGovUk/Controllers/Company/Pscs.pm
- templates/company/pscs/list.html.tx
Add paging to the PSC page on CHS
Resolves: BI-8123
> BI-8123 - Add ability to page through PSC results

- lib/ChGovUk/Controllers/Company/Pscs.pm
> Fix bug where additional psc pages added due to statements

- templates/company/pscs/list.html.tx
> BI-8273 - Fix issue where pscs and statements results combined cause page numbers to show

- templates/company/pscs/list.html.tx
> BI-1832 - Ensure pscs and statements count only shows on page 1

- templates/includes/insolvency_case_dates.tx
Amendments for moratorium end date
Resolves BI-8374
> Amendments for moratorium end date

- appconfig.yml
- templates/company/view_all/view.html.tx
> Rework urls for certificates, dissolved certs and certified docs

- templates/base.tx
Add class to footer, fix certified copies layout
> GovUK Frontend Upgrades

- templates/base.tx
> update built by link to gov website ch page

- templates/company/view_all/view.html.tx
> remove unused css class and update class name for hidden text

- templates/company/company_name_availability/form.html.tx
- templates/company/transactions/transaction.tx
- templates/includes/transactions.tx
- templates/search/results.html.tx
fix page titles set text page titles where the title was cascaded to the fragment
Resolves: CHS-2031
> fix page titles 

- templates/company/company_name_availability/form.html.tx
- templates/company/transactions/transaction.tx
fix change of roa page header 
make name availability checker page title dynamic
Resolves: CHS-2031
> Fix page titles

- templates/company/company_name_availability/form.html.tx
> update name checker page title logic

- templates/company/company_name_availability/form.html.tx
> potential logic fix

- lib/ChGovUk/Controllers/Search.pm
- lib/ChGovUk/Controllers/Search/CompanyNameAvailability.pm
- templates/company/company_name_availability/form.html.tx
- templates/search/results.html.tx
> fix page title move logic into controllers

- lib/ChGovUk/Controllers/Search/CompanyNameAvailability.pm
- templates/company/branches/view.html.tx
- templates/company/mortgages/view_details.html.tx
- templates/company/registers/members/list.html.tx
- templates/company/registers/secretaries/list.html.tx
update name checker to pass title on initial render 
update page titles on further pages
Resolves: CHS-2031
> Update page titles

- appconfig.yml
- templates/search/form.tx
> Add advanced search link

- templates/base.tx
- templates/company/company_name_availability/form.html.tx
- templates/company/pscs/list.html.tx
- templates/includes/transaction.tx
- templates/includes/transactions.tx
- templates/not_found.production.html.tx
- templates/search/banner.tx
- templates/search/form.tx
- templates/search/js-tabs.tx
- templates/search/results.html.tx
- templates/search/tabs.tx
- templates/static_pages/help/feedback.html.tx
> BI-8876 - Frontend upgrade mop up fixes for ch.gov.uk

- templates/company/view_all/view.html.tx
> BI-9157 - Fix button highlighting for ordering certificates and certified documents

- templates/company/filing_history/view_content.html.tx
> Attempt to fix pdf link

- templates/static_pages/help/accessibility-statement.html.tx
BI-9566
Removed the Welsh language telephone number from the accessibility statement
> Remove Welsh language telephone number

- templates/base.tx
- templates/static_pages/help/accessibility-statement.html.tx
BI-9564
Remove number format exclusion for smart phones on accessibility page
> Remove number format exclusion for smart phones on accessibility page

- templates/base.tx
BI-9565
Amended contact us link, added screen reader tags for contact us, policies and developers links
> Amend contact us URL, add screen reader tags

- templates/base.tx
BI-9565
Amended to open contact us in another tab
> Amended to open contact us in another tab

- templates/static_pages/help/accessibility-statement.html.tx
BI-9564
Added hyperlink to perform telephone call
> Added hyperlink to perform telephone call

- templates/company/officers/list.html.tx
remove displaying active status for officers in a closed company
Resolves: BI-9620
> remove displaying active status for officers in a closed company

- templates/static_pages/help/cookies.html.tx
This PR updates the content on the cookies page.
**Resolves:**
- BI-10057
> Update cookies page

- templates/company/partial_data_available/view.html.tx
BI-10082 Amend URL for Mutuals Public Register - company profile for registered societies
> Amend URL for Mutuals Public Register - company profile for registered societies

- templates/search/banner.tx
- templates/search/form.tx
- templates/search/noresults.html.tx
BI-10200 Update text on No results found page - primary search
> Update text on No results found page - primary search

- lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
- templates/company/filing_history/view_content_certified.html.tx
Add additional check to stop ordering of PRE95 or PRE95M certified documents
Resolves: BI-10160
> Bi 10160 pre 95 doc check

- templates/search/banner.tx
- templates/search/form.tx
- templates/search/noresults.html.tx
BI-10200 update text on no results found page-Primary search.
> updated company-text to results on no results found page

- templates/company/filing_history/view_content_certified.html.tx
BI-10160
Changed PRE95 check to be first check performed
> Changed PRE95 check to be first check performed

- templates/company/filing_history/view_content_certified.html.tx
> remove extra exclamation for pre95m

- templates/company/filing_history/view_content_certified.html.tx
> changed logic to AND for pre95 and pre95m check

- templates/company/filing_history/view_content.html.tx
- templates/includes/company/page_header.tx
- templates/includes/company/people_tabs.tx
- templates/includes/company/tab.tx
Updates to ch.gov.uk links and buttons to ensure a consistent govuk styling.
Resolves: BI-10371
> BI-10371 - Update links and buttons to match govuk style guide

- templates/company/view_all/view.html.tx
BI-10508
Amended the text for the company snapshot information text
> Amended the text for the company snapshot information text

- appconfig.yml
- lib/ChGovUk/Controllers/Company/ViewAll.pm
- t/unit/ChGovUk/Controllers/Company/ViewAll.t
* Render order a certified certificate button on more tab if company
status is 'administration' and ORDER_ADMINISTRATION_CERTIFICATE
feature flag is enabled.
Resolves:
[BI-8853](https://companieshouse.atlassian.net/browse/BI-8853)
> BI-8853 Display order certificate for companies in admin

- templates/company/view.html.tx
ROE-30 Update ch gov uk (web template) to handle ROE
> Update web template ch gov uk

- templates/company/view.html.tx
ROE-30 Update ch.gov.uk (web template) to handle ROE information
> removed unnecessary line and added companyType.

- lib/CH/Util/CompanyPrefixes.pm
- templates/company/view.html.tx
> ROE-85 - Further align ROE company profile screens

- templates/personal_appointments/get.html.tx
Add managing officer sections to personal appointments
Resolves: ROE-228
> ROE-228 - Add managing officer details sections to personal appointments

- templates/personal_appointments/get.html.tx
> GCI-2108 - Fix empty h3 accessibility issue

- templates/company/pscs/list.html.tx
output super secure beneficial owner description
Resolves: ROE-367
> Roe 367 output bo on chs psc page

- templates/company/pscs/list.html.tx
amend layout of psc/bo data 
Resolves: ROE-367
> update layout of psc and bo data

- templates/company/pscs/list.html.tx
add additional check for removed company status for roe bos active tag removal
Resolves: GCI-2116
> add additional check for removed company status for roe bos active 

- templates/company/pscs/list.html.tx
add check for removed roe company status to output correct text for bo's
Resolves: GCI-2116
> add check for removed roe company status to output correct text for bo

- templates/company/pscs/list.html.tx
update logic for statements text for removed company status
Resolves: GCI-2116
> update logic for statements text for removed company status

- templates/company/pscs/list.html.tx
add removed status for statements active tag output for roe
Resolves: GCI-2116
> add removed status for statements active tag output for roe

- lib/ChGovUk/Plugins/AddressHelper.pm
ROE-608: Ammend ch-gov-uk to handle single name item in contact_details object
> ROE-608: Ammend ch-gov-uk to handle single name item in contact_details object

- templates/company/pscs/list.html.tx
updated logic to output bo data if fields missing
Resolves: GCI-2120
> updated logic to output bo data if fields missing

- templates/personal_appointments/get.html.tx
Update page headings for MO's personal appointments.
Resolves: ROE-830
> ROE-830 - Amend mo personal appointments field headings

- templates/personal_appointments/get.html.tx
Fixes personal appointments rendering error.
> Add missing { to fix template issue

- templates/company/officers/list.html.tx
ROE-829:Amend Appointed on and Resigned on references in web display for  Company officers
> ROE-829:Amend Appointed on and Resigned on references in web display for  Company officers

- templates/company/officers/list.html.tx
ROE-865 -change Ceased on date on the officers tab for a managing officert to the resigned on date
> Changed the resigned on date from appointed on date

- templates/company/officers/list.html.tx
Add section for super secure managing officers to detail the number of super secure mo's and what that means.
Resolves: ROE-1021
> ROE-1021 - Add super secure managing officer descriptions

- templates/company/filing_history/view_content_certified.html.tx
remove fee column from cert copies filing history selection screen
Resolves: BI-11404
> remove fee column from cert copies filing history selection screen

- lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
BI-11398 - redirect from delivery details to delivery options
> redirect from delivery details to delivery options

- templates/static_pages/help/feedback.html.tx
Amendment to show the sign in link on feedback page
BI-11587
> Amendment to show the sign in link on feedback page

- templates/base.tx
- templates/static_pages/help/guidance.html.tx
**DO NOT MERGE UNTIL BROUGHT INTO SPRINT**
> BI-11585: Display sign in banner on accounts guidance page

- templates/static_pages/help/other-filings.html.tx
Amendment to enable the user bar on the other filings page
BI-11584
> Amendment to enable the user bar on the other filings page

- templates/company/filing_history/view_certified.html.tx
BI-11521 - Add user sign in bar
> Add user signin bar to certified documents page

- lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
- templates/company/filing_history/view_content_certified.html.tx
* Certified copy items will now be added to the user's basket by the
delivery options/email options page(s).
> GCI-2255 Remove logic to add certified copy to basket

- templates/base.tx
Amended the link for the "Tell us what you think of this service" link
BI-11502
> Changed link url

- templates/company/branches/view.html.tx
- templates/company/filing_history/view.html.tx
- templates/company/insolvency/view.html.tx
- templates/company/mortgages/view.html.tx
- templates/company/mortgages/view_details.html.tx
- templates/company/officers/list.html.tx
- templates/company/partial_data_available/view.html.tx
- templates/company/pscs/list.html.tx
- templates/company/registers/directors/list.html.tx
- templates/company/registers/list.html.tx
- templates/company/registers/members/list.html.tx
- templates/company/registers/pscs/list.html.tx
- templates/company/registers/secretaries/list.html.tx
- templates/company/view.html.tx
- templates/company/view_all/view.html.tx
- templates/includes/company/tab.tx
- templates/includes/company/tabs.tx
- templates/includes/company/tabs_end.tx
- templates/includes/company/tabs_start.tx
> GCI-2228 - Align CHS tabs with gov.uk design

- templates/includes/transactions.tx
add text to hidden th tag to resolve wave errors
Resolves: GCI-2231
> add text to hidden th tag to resolve wave errors

- templates/static_pages/help/accessibility-statement.html.tx
GCI-2246 - Update accessibility statement
> Made changes to update accessibiity satatement

- templates/includes/transactions.tx
> update actions table header

- templates/static_pages/help/accessibility-statement.html.tx
GCI-2246 - Update accessibility statement
> Added more updates to the accessibility update

- templates/static_pages/help/accessibility-statement.html.tx
GCI-2246 - update accessibility statement
> Minor change added to remove fullstop and uppercase change

- templates/company/view.html.tx
- Reintroduce date but with alignment fix
- Fix previous names section getting misaligned
> Rework fix for company overview tab

- templates/company/registers/list.html.tx
Registers tab panel fix which ensures all content is within the tab panel.
> Fix registers tab panel 

- templates/includes/transactions.tx
Check company number is present on transactions list
> Add additional check to your filings transactions list

- templates/company/view.html.tx
**This must not be merged until the story is in sprint.**
> BI-11783: Remove opened on date from UK establishment

- templates/admin/transaction/search_by_company_number.html.tx
- templates/search/noresults.html.tx
* Only changed the two instances in this application that seem to be in use at this point.
* Please read this [FYI comment](https://companieshouse.atlassian.net/browse/GCI-2254?focusedCommentId=200587) as part of review.
> GCI-2254: Add status role to "No results found" message

- templates/search/banner.tx
- templates/search/form.tx
- templates/search/js-tabs.tx
- templates/search/noresults.html.tx
- templates/search/results.html.tx
- templates/search/tabs.tx
Added govuk-link style class to hyperlinks
BI-11370
> Added govuk-link style class to hyperlinks

- templates/company/company_name_availability/form.html.tx
* Please view in conjunction with this [other PR](https://github.com/companieshouse/cdn.ch.gov.uk/pull/532), which these changes depend on.
> BI-11373: Name availability checker GDS highlighting

- templates/static_pages/help/feedback.html.tx
* Making the changes to `feedback.html.tx` seems to have the desired effect.
* However, there is a similar file `feedback.tx`. 
* Do we need to change that too? If so, how do we test it?
> BI-11376: Customer feedback GDS highlighting

- templates/search/banner.tx
- templates/search/form.tx
- templates/search/js-tabs.tx
- templates/search/noresults.html.tx
- templates/search/results.html.tx
- templates/search/tabs.tx
Reverted previous fixes to fix primary search
BI-11370
> Reverted previous fixes to fix primary search

- templates/company/company_name_availability/form.html.tx
- templates/search/banner.tx
- templates/search/form.tx
- templates/search/js-tabs.tx
- templates/search/results.html.tx
- templates/search/tabs.tx
Apply GDS highlighting to primary search
BI-11370
> Bi 11370 apply highlighting

- templates/base.tx
- templates/company/officers/list.html.tx
- templates/company/registers/secretaries/list.html.tx
- templates/search/results.html.tx
Amendments for GDS highlighting on officer results
BI-11500
> Amendments for GDS highlighting on officer results

- templates/company/mortgages/view_content.html.tx
Amendment to enable GDS highlighting on charges links
BI-11500
> Amendment to enable GDS highlighting on charges links

- templates/search/banner.tx
- templates/search/form.tx
- templates/search/noresults.html.tx
- templates/search/results.html.tx
BI-11499 - GDS styling to report a disqualified director and register of disqualifications links
> Add GDS styling to report a disqualified director and register of disqualifications links

- templates/company/filing_history/view_content.html.tx
Amendments to add text for screen readers
BI-11874
> Amendments to add text for screen readers

- templates/company/filing_history/view_content.html.tx
Amendments to correct text to speech for MID Request document links
BI-11874
> Amendments to correct text to speech for MID Request document links

- templates/company/filing_history/view_content.html.tx
Removed spaces in the Request document link
BI-11874
> Removed spaces in the Request document link

- templates/register_of_disqualifications/list.html.tx
- templates/search/results.html.tx
BI-11499 - Amendment to resolve pagination on register of disqualifications page
> Amendment to correct pagination on register of disqualifications page

- templates/register_of_disqualifications/list.html.tx
- templates/search/results.html.tx
BI-11499 - removed extra space between classes
> remove extra space between classes

- lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
> Add basket link to user nav bar for certified documents filing history page

- lib/ChGovUk/Bridge/Company.pm
- lib/ChGovUk/Controllers/Company/CertifiedDocuments.pm
- lib/ChGovUk/Controllers/Search.pm
- lib/ChGovUk/Controllers/Search/CompanyNameAvailability.pm
- Add basket link to company detail and search pages
- Remove error screens for when basket not available
- Remove redundant code blocking basket link when no search query included
Resolves: BI-11906
> Add basket to company detail and search pages

- lib/ChGovUk/Controllers/Company/ViewAll.pm
> BI-11509 - Enable eeig companies to generate snapshots

- lib/ChGovUk/Controllers/Admin/User/Filings.pm
- lib/ChGovUk/Controllers/BasketLinkController.pm
* Explored the possibility of verifying this new behaviour **again** in automated tests and concluded **once again** it would be too time-consuming. :(
> BI-12091: Display basket link on 'Your filings' page

- templates/company/filing_history/view_certified.html.tx
Resolves BI-11973 and BI-11974
Enable feedback link on certified document page
> add feedback link to certified documents page

- appconfig.yml
[ROE-2025](https://companieshouse.atlassian.net/browse/ROE-2025)
[ROE-2026](https://companieshouse.atlassian.net/browse/ROE-2026)
ROE-2025 ROE-2026 Add URL for authcode request page to app configuration
[ROE-2025]: https://companieshouse.atlassian.net/browse/ROE-2025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ROE-2026]: https://companieshouse.atlassian.net/browse/ROE-2026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ROE-2025 ROE-2026 Add URL for authcode request page

- templates/includes/company/page_header.tx
Resolves: ECCT-463
Stylesheet PR: https://github.com/companieshouse/cdn.ch.gov.uk/pull/573
> ECCT-463 - Add Corporate annotations to CHS

- lib/ChGovUk/Models/Address.pm
- lib/ChGovUk/Models/Company/Transactions/ChangeRegisteredOfficeAddress.pm
Added statement flag in api message - field accept_appropriate_office_address_statement
set to true when checkbox is ticked, not included otherwise.
> Pass statement field to api [ECCT-634]

- errors.yml
Added validation message for statement - depends on roa-api changes
> Add validation message for statement [ECCT-689]

- lib/ChGovUk/Models/Address.pm
Updated json type used to match what roa-api will be expecting.
> Use boolean constant for true [ECCT-634]

- t/unit/ChGovUk/Plugins/AddressHelper.t
https://companieshouse.atlassian.net/browse/PAS-388
Fix tests in AddressHelper
> PAS-388 Fix tests in AddressHelper

- t/unit/ChGovUk/Plugins/AddressHelper.t
https://companieshouse.atlassian.net/browse/PAS-388
> Change conditionals to suit strict subs

- templates/company/view.html.tx
BI-13607:Update link on the company profile for Charitable incorporated organisations
> Update link on the company profile for Charitable incorporated organisations

- templates/includes/company/page_header.tx
- templates/search/form.tx
Fulfils [BI-13609](https://companieshouse.atlassian.net/browse/BI-13609) and [BI-13611](https://companieshouse.atlassian.net/browse/BI-13611)
- Update form label on CHS homepage 
- Remove unnecessary p tags
- Remove 'Start here...' placeholder text
- Give page heading H1 tags
[BI-13609]: https://companieshouse.atlassian.net/browse/BI-13609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-13611]: https://companieshouse.atlassian.net/browse/BI-13611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-13609/BI-13611 - Various accessibility changes

- templates/company/filing_history/view.html.tx
BI-13612: Update the fieldset for radio buttons on the filing history page
> Update the fieldset for radio buttons on the filing history page

- templates/company/filing_history/view.html.tx
BI-13612: Update the fieldset for radio buttons on the filing history page
> move fieldset towards end of form

- templates/includes/cookie-consent-banner.tx
Fulfils [BI-13663](https://companieshouse.atlassian.net/browse/BI-13663)
[BI-13663]: https://companieshouse.atlassian.net/browse/BI-13663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-13663 - Fix cookie links within CHS

- templates/search/tabs.tx
BI-13610:Update form labels on company search pages
> BI-13610:Update form labels on company search pages

- templates/search/tabs.tx
BI-13610: Update form labels on company search pages
> Update form labels on company search pages

- templates/company/filing_history/view.html.tx
BI-13612:Update the fieldset for radio buttons on the filing history page
> BI-13612:Update the fieldset for radio buttons on the filing history page

- templates/base.tx
- templates/register_of_disqualifications/list.html.tx
BI-13629:Update Target size of letters links on register of disqualifications page
> Update Target size of letters links on register of disqualifications page

- lib/ChGovUk/Controllers/Search.pm
use uri_escape_utf8 to escape query parameter
> BI-13686: use uri_escape_utf8 to encode query

- Tiltfile.dev
- templates/search/results.html.tx
BI-13628:Update target size of page numbers on search results page
> Update target size of page numbers on search results page

- templates/search/results.html.tx
BI-13628:Adjust styling to match GDS styling
> Adjust styling to match GDS styling

- templates/company/view_all/view.html.tx
BI-13975:Update Company profile more tab to remove "of incorporation" from certificate content
> Update Company profile more tab to remove "of incorporation" from certificate content

- templates/company/view_all/view.html.tx
BI-13994:Update certificate content on more tab on company profile
> Update certificate content on more tab on company profile

- templates/static_pages/help/accessibility-statement.html.tx
Resolves [BI-14073](https://companieshouse.atlassian.net/browse/BI-14073) 
- Make changes to update the text content to match document 
- Change hyperlink to link to version 2.2 of w3 guidelines
[BI-14073]: https://companieshouse.atlassian.net/browse/BI-14073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-14073-Update accessibility statement within chs

- templates/search/results.html.tx
BI-13628:Update target size of page numbers on search results page
> Add class to display all page numbers rather than hide some

- templates/company/filing_history/view_content.html.tx
- templates/company/filing_history/view_content_certified.html.tx
- templates/company/officers/list.html.tx
- templates/company/pscs/list.html.tx
> BI-13628 filing history page

- templates/company/filing_history/view_content.html.tx
- templates/company/filing_history/view_content_certified.html.tx
- templates/company/officers/list.html.tx
- templates/company/pscs/list.html.tx
BI-13628:Update next and previous buttons to redirect to the appropriate page
> Update next and previous buttons to redirect to the appropriate page

- templates/register_of_disqualifications/list.html.tx
BI-14092:Add pagination to register of disqualifications page
> Add pagination to register of disqualifications page

- lib/ChGovUk/Controllers/Company/Insolvency.pm
Fix call to $error variable which is never set
> Fix call to non set variable

- templates/base.tx
Changes made to the base.tx file
> IDVA3-2637

- templates/base.tx
Changed the text from "Manage details" to "Manage Account"
> IDVA3-2718: changes

- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
- terraform/groups/ecs-service/variables.tf
Added vars to set scaling cooldowns, scale out set to `120`
Lowered service minimum tasks
> Update scaling settings

- terraform/groups/ecs-service/main.tf
Bumps all module version  from `303` to `304`
> Bump module versions

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
- terraform/groups/ecs-service/variables.tf
Update task CPU and Mem balance between app and eric
Updated task counts
Set CPU scaling threshold
> Update Task Configs

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
* Enables testing in Mesos.
* Will be reverted once testing has been completed.
[BI-14445](https://companieshouse.atlassian.net/browse/BI-14445)
[BI-14445]: https://companieshouse.atlassian.net/browse/BI-14445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-14445: Disable ECS listeners in CIDEV and Staging

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
* To be merged in after CIDEV and Staging Mesos testing has been completed.
* Reverts companieshouse/ch.gov.uk#540
[BI-14445](https://companieshouse.atlassian.net/browse/BI-14445)
[BI-14445]: https://companieshouse.atlassian.net/browse/BI-14445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-14445: Re-enable ECS listeners in CIDEV and Staging

- lib/ChGovUk/Plugins/CVConstants.pm
- templates/base.tx
Change Manage account link for updated wording.
> IDVA3-2981: Update 'Manage account' link content

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
CC-2244 Switch from ECS to Mesos for testing
> CC-2244 Switch from ECS to Mesos for testing

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
CC-2244 Switch to Mesos in Staging for testing and back to ECS in CIDEV as the default
> CC-2244 Switch to Mesos in Staging and ECS in CIDEV

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
Pin task counts
Disable auto-scaling config
Enable listeners for `officers` and `search`
> Enable live listeners

- lib/ChGovUk/Bridge/Company.pm
CC-2758 Relax regex to 8 alphanumeric (uppercase) characters
NINI5636
IPIP316C
SP3COLLS
SP2COLLS
SP4COLLS
IPIP2960
LP0P2196
OC0P223R
> CC-2758 Relax regex to 8 alphanumeric (uppercase) characters

- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/variables.tf
Add vars and update service configs to allow task-level healthchecks to be enabled or disabled on a per-service basis
> Per-service Task Healthchecks

- lib/ChGovUk/Bridge/Company.pm
> Add add additional debugging to company bridge module.

- lib/ChGovUk/Bridge/Company.pm
Reverts companieshouse/ch.gov.uk#581
> Revert "Add add additional debugging to company bridge module."

- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> switch staging back to ECS after testing REL0004743

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
Set task limits in Live for Search service
> Set Search service task sizing

- lib/ChGovUk/Controllers/Company/Officers.pm
- templates/company/officers/list.html.tx
Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-717
Changes:
- ACSP note added to the template
> SIV-717 Frontend - Officers - ACSP Note

- lib/ChGovUk/Controllers/PersonalAppointments.pm
- templates/personal_appointments/get.html.tx
Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-742
Changes:
- Identity verification details added to personal appointments
> SIV-742 frontend officers officer companies view

- lib/ChGovUk/Controllers/Company/Pscs.pm
- templates/company/officers/list.html.tx
- templates/company/pscs/list.html.tx
- templates/personal_appointments/get.html.tx
Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-720
Changes:
- Identity verification details ACSP note added to PSC
> SIV-720 Frontend - PSC - ACSP Note

- templates/company/pscs/list.html.tx
Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-719
Changes:
- Identity verification details added to the PSC template
> SIV-719 Frontend - PSC - Identity verification status

- appconfig.yml
- templates/company/officers/list.html.tx
- templates/company/pscs/list.html.tx
- templates/personal_appointments/get.html.tx
Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-832
Changes:
- Feature flag added for idv details
> SIV-832 Feature flag added for idv details
